### ISSUE TITLE
Unable to load Gradle JavaEE plugin?

### ISSUE THREAD

**Issue by teras** [hildo/netbeans-gradle-javaee-project#14] opened 2014-12-31 12:21 UTC
I am successful with the generic Gradle plugin, but I'd like to use it in a JavaEE project, but there are some problems.
I suspect that the plugin does not kick in, and I don't know why.

As you said in a previous post, if the layout is like this:
![screen shot 2014-12-31 at 2 18 59 pm](https://cloud.githubusercontent.com/assets/592568/5587594/10032008-90f8-11e4-8e9f-b4e9df0f7a1d.png)
then the plugin is not loaded.

What are the requirements to understand this project as a JavaEE project?

If the project will be recognized, then will the Glassfish deployment & debugging be performed?

**Comment by 38leinaD** [comment] 2016-10-11 06:23
>  I'd prefer Netbeans to automatically attach the debugger to glassfish. I know that I can do this myself, but (again) is a missing feature that makes gradle totally alien to the Netbeans platform.

Exactly, i am also missing this core feature or deploying/running the war from within netbeans; just like maven is integrated into netbeans.

**Comment by 38leinaD** [comment] 2016-10-15 14:53
The problem i am getting right now when opening a gradle war project is this:

Issue 1
--------

  Requested project: C:\Users\daniel.platz\dev\sandbox\webapp
  Actual project: :
  Extension: og.netbeans.gradle.javaee.jpa.JpaModuleExtensionDef
  Model builder: 

  Stack trace:
    org.netbeans.gradle.model.util.TransferableExceptionWrapper: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.netbeans.gradle.javaee.jpa.model.NbJpaModelBuilder
    	at org.netbeans.gradle.model.internal.SerializedEntries.getUnserialized(SerializedEntries.java:25)
    	at org.netbeans.gradle.model.GradleInfoQueryMap$Deserializer.deserialize(GradleInfoQueryMap.java:241)
    	at org.netbeans.gradle.model.internal.ModelQueryInput.getProjectInfoRequests(ModelQueryInput.java:21)
    	at org.netbeans.gradle.model.internal.DynamicModelLoader.fetchProjectInfos(DynamicModelLoader.java:39)
    	at org.netbeans.gradle.model.internal.DynamicModelLoader.buildAll(DynamicModelLoader.java:129)
    	at org.gradle.tooling.internal.provider.runner.DefaultBuildController.getModel(DefaultBuildController.java:72)
    	at org.gradle.tooling.internal.consumer.connection.BuildControllerAdapter.getModel(BuildControllerAdapter.java:74)
    	at org.gradle.tooling.internal.consumer.connection.BuildControllerAdapter.getModel(BuildControllerAdapter.java:43)
    	at org.netbeans.gradle.model.GenericModelFetcher$1.findModel(GenericModelFetcher.java:249)
    	at org.netbeans.gradle.model.GenericModelFetcher.getModel(GenericModelFetcher.java:239)
    	at org.netbeans.gradle.model.GenericModelFetcher.getModelOutput(GenericModelFetcher.java:266)
    	at org.netbeans.gradle.model.GenericModelFetcher.access$100(GenericModelFetcher.java:39)
    	at org.netbeans.gradle.model.GenericModelFetcher$AllProjectInfoBuilder.addCustomInfo(GenericModelFetcher.java:395)
    	at org.netbeans.gradle.model.GenericModelFetcher$AllProjectInfoBuilder.<init>(GenericModelFetcher.java:385)
    	at org.netbeans.gradle.model.GenericModelFetcher$ModelFetcherBuildAction.executeUnsafe(GenericModelFetcher.java:328)
    	at org.netbeans.gradle.model.GenericModelFetcher$ModelFetcherBuildAction.execute(GenericModelFetcher.java:351)
    	at org.netbeans.gradle.model.GenericModelFetcher$ModelFetcherBuildAction.execute(GenericModelFetcher.java:276)
    	at org.gradle.tooling.internal.consumer.connection.InternalBuildActionAdapter.execute(InternalBuildActionAdapter.java:40)
    	at org.gradle.tooling.internal.provider.runner.ClientProvidedBuildActionRunner.run(ClientProvidedBuildActionRunner.java:53)
    	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
    	at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:58)
    	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
    	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
    	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
    	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:79)
    	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:51)
    	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:59)
    	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
    	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
    	at org.gradle.util.Swapper.swap(Swapper.java:38)
    	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
    	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
    	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.HintGCAfterBuild.execute(HintGCAfterBuild.java:44)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
    	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:293)
    	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
    	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: org.netbeans.gradle.model.util.TransferableExceptionWrapper: java.lang.ClassNotFoundException: org.netbeans.gradle.javaee.jpa.model.NbJpaModelBuilder
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    	at java.lang.Class.forName0(Native Method)
    	at java.lang.Class.forName(Class.java:348)
    	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:628)
    	at org.netbeans.gradle.model.util.SerializationUtils$CustomClassObjectInputStream.resolveClass(SerializationUtils.java:90)
    	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1620)
    	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
    	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1781)
    	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
    	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
    	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
    	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
    	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
    	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
    	at java.util.ArrayList.readObject(ArrayList.java:791)
    	at sun.reflect.GeneratedMethodAccessor79.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
    	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1909)
    	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
    	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
    	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
    	at org.netbeans.gradle.model.util.SerializationUtils.deserializeObject(SerializationUtils.java:69)
    	at org.netbeans.gradle.model.internal.SerializedEntries.getUnserialized(SerializedEntries.java:21)
    	... 56 more
    

Issue 2
--------

  Requested project: C:\Users\daniel.platz\dev\sandbox\webapp
  Actual project: :
  Extension: org.netbeans.gradle.javaee.web.WebModuleExtensionDef
  Model builder: 

  Stack trace:
    org.netbeans.gradle.model.util.TransferableExceptionWrapper: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.netbeans.gradle.javaee.web.model.NbWebModelBuilder
    	at org.netbeans.gradle.model.internal.SerializedEntries.getUnserialized(SerializedEntries.java:25)
    	at org.netbeans.gradle.model.GradleInfoQueryMap$Deserializer.deserialize(GradleInfoQueryMap.java:241)
    	at org.netbeans.gradle.model.internal.ModelQueryInput.getProjectInfoRequests(ModelQueryInput.java:21)
    	at org.netbeans.gradle.model.internal.DynamicModelLoader.fetchProjectInfos(DynamicModelLoader.java:39)
    	at org.netbeans.gradle.model.internal.DynamicModelLoader.buildAll(DynamicModelLoader.java:129)
    	at org.gradle.tooling.internal.provider.runner.DefaultBuildController.getModel(DefaultBuildController.java:72)
    	at org.gradle.tooling.internal.consumer.connection.BuildControllerAdapter.getModel(BuildControllerAdapter.java:74)
    	at org.gradle.tooling.internal.consumer.connection.BuildControllerAdapter.getModel(BuildControllerAdapter.java:43)
    	at org.netbeans.gradle.model.GenericModelFetcher$1.findModel(GenericModelFetcher.java:249)
    	at org.netbeans.gradle.model.GenericModelFetcher.getModel(GenericModelFetcher.java:239)
    	at org.netbeans.gradle.model.GenericModelFetcher.getModelOutput(GenericModelFetcher.java:266)
    	at org.netbeans.gradle.model.GenericModelFetcher.access$100(GenericModelFetcher.java:39)
    	at org.netbeans.gradle.model.GenericModelFetcher$AllProjectInfoBuilder.addCustomInfo(GenericModelFetcher.java:395)
    	at org.netbeans.gradle.model.GenericModelFetcher$AllProjectInfoBuilder.<init>(GenericModelFetcher.java:385)
    	at org.netbeans.gradle.model.GenericModelFetcher$ModelFetcherBuildAction.executeUnsafe(GenericModelFetcher.java:328)
    	at org.netbeans.gradle.model.GenericModelFetcher$ModelFetcherBuildAction.execute(GenericModelFetcher.java:351)
    	at org.netbeans.gradle.model.GenericModelFetcher$ModelFetcherBuildAction.execute(GenericModelFetcher.java:276)
    	at org.gradle.tooling.internal.consumer.connection.InternalBuildActionAdapter.execute(InternalBuildActionAdapter.java:40)
    	at org.gradle.tooling.internal.provider.runner.ClientProvidedBuildActionRunner.run(ClientProvidedBuildActionRunner.java:53)
    	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
    	at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:58)
    	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
    	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
    	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
    	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:79)
    	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:51)
    	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:59)
    	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
    	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
    	at org.gradle.util.Swapper.swap(Swapper.java:38)
    	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
    	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
    	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.HintGCAfterBuild.execute(HintGCAfterBuild.java:44)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
    	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:293)
    	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
    	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: org.netbeans.gradle.model.util.TransferableExceptionWrapper: java.lang.ClassNotFoundException: org.netbeans.gradle.javaee.web.model.NbWebModelBuilder
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    	at java.lang.Class.forName0(Native Method)
    	at java.lang.Class.forName(Class.java:348)
    	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:628)
    	at org.netbeans.gradle.model.util.SerializationUtils$CustomClassObjectInputStream.resolveClass(SerializationUtils.java:90)
    	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1620)
    	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
    	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1781)
    	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
    	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
    	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
    	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
    	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
    	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
    	at java.util.ArrayList.readObject(ArrayList.java:791)
    	at sun.reflect.GeneratedMethodAccessor79.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
    	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1909)
    	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
    	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
    	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
    	at org.netbeans.gradle.model.util.SerializationUtils.deserializeObject(SerializationUtils.java:69)
    	at org.netbeans.gradle.model.internal.SerializedEntries.getUnserialized(SerializedEntries.java:21)
    	... 56 more

Can anyone with more NB experience give me a hint where to look? the plugin seems installed and the jar/classes should be on the classpath...

**Comment by kelemen** [comment] 2016-10-15 15:00
This is a bug in the core Gradle plugin and was fixed in the last update. However, the last update is not verified yet, so you can not download it yet from the plugins dialog. You have to dowload and install it manually from http://plugins.netbeans.org/plugin/44510

**Comment by 38leinaD** [comment] 2016-10-15 15:06
awesome! works :-)

**Closed** 2018-01-24 14:28 UTC
